[package]
name = "space_simulation"
version = "0.1.0"
authors = ["Tai Danh <taid100@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
